<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Governorate;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Cities/markaz per governorate (keyed by Governorate.slug).
     * Each entry is [arabic_name, english_name].
     */
    private array $citiesByGovernorate = [
        'alexandria' => [
            ['الإسكندرية', 'Alexandria'],
            ['برج العرب', 'Borg El Arab'],
            ['العامرية', 'Al Amreya'],
            ['أبو قير', 'Abu Qir'],
            ['المنتزه', 'El Montaza'],
            ['سيدي جابر', 'Sidi Gaber'],
            ['المنشية', 'El Manshiya'],
            ['وسط المدينة', 'Downtown Alexandria'],
            ['العجمي', 'El Agamy'],
            ['كرموز', 'Karmouz'],
        ],
        'assiut' => [
            ['أسيوط', 'Assiut'],
            ['ديروط', 'Dayrout'],
            ['منفلوط', 'Manfalut'],
            ['القوصية', 'El Qusiya'],
            ['أبو تيج', 'Abu Tig'],
            ['ساحل سليم', 'Sahel Selim'],
            ['أبنوب', 'Abnub'],
            ['الفتح', 'El Fath'],
            ['الغنايم', 'El Ghanayem'],
            ['صدفا', 'Sidfa'],
            ['البداري', 'El Badari'],
        ],
        'aswan' => [
            ['أسوان', 'Aswan'],
            ['دراو', 'Daraw'],
            ['كوم أمبو', 'Kom Ombo'],
            ['إدفو', 'Edfu'],
            ['نصر النوبة', 'Nasr El Nuba'],
            ['كلابشة', 'Kalabsha'],
            ['أبو سمبل', 'Abu Simbel'],
            ['السباعية', 'El Sebaiya'],
        ],
        'beheira' => [
            ['دمنهور', 'Damanhour'],
            ['كفر الدوار', 'Kafr El Dawwar'],
            ['رشيد', 'Rosetta'],
            ['إدكو', 'Idku'],
            ['أبو حمص', 'Abu Hummus'],
            ['أبو المطامير', 'Abu El Matamir'],
            ['حوش عيسى', 'Hosh Issa'],
            ['شبراخيت', 'Shubrakhit'],
            ['كوم حمادة', 'Kom Hamada'],
            ['إيتاي البارود', 'Itay El Barud'],
            ['الدلنجات', 'El Delengat'],
            ['المحمودية', 'El Mahmoudia'],
            ['وادي النطرون', 'Wadi El Natrun'],
            ['النوبارية الجديدة', 'New Nubaria'],
            ['بدر', 'Badr'],
        ],
        'beni-suef' => [
            ['بني سويف', 'Beni Suef'],
            ['الواسطى', 'Al Wasta'],
            ['ناصر', 'Naser'],
            ['إهناسيا', 'Ihnasya'],
            ['ببا', 'Beba'],
            ['سمسطا', 'Sumusta'],
            ['الفشن', 'Al Fashn'],
            ['بني سويف الجديدة', 'New Beni Suef'],
        ],
        'cairo' => [
            ['القاهرة', 'Cairo'],
            ['حلوان', 'Helwan'],
            ['المعادي', 'Maadi'],
            ['مدينة نصر', 'Nasr City'],
            ['القاهرة الجديدة', 'New Cairo'],
            ['مصر الجديدة', 'Heliopolis'],
            ['شبرا', 'Shubra'],
            ['الزمالك', 'Zamalek'],
            ['وسط البلد', 'Downtown Cairo'],
            ['السلام', 'El Salam'],
            ['المرج', 'El Marg'],
            ['عين شمس', 'Ain Shams'],
            ['مدينتي', 'Madinaty'],
            ['شيراتون', 'Sheraton'],
            ['جاردن سيتي', 'Garden City'],
            ['مصر القديمة', 'Old Cairo'],
            ['المطرية', 'El Matareya'],
            ['المقطم', 'El Mokattam'],
            ['الرحاب', 'El Rehab'],
            ['التجمع الخامس', 'Fifth Settlement'],
            ['العبور', 'El Obour'],
            ['العاشر من رمضان', '10th of Ramadan'],
            ['بدر', 'Badr City'],
            ['المنيل', 'El Manial'],
            ['السيدة زينب', 'El Sayeda Zeinab'],
            ['الزيتون', 'El Zeitoun'],
            ['الموسكي', 'El Mouski'],
            ['الأزبكية', 'El Azbakeya'],
            ['الدرب الأحمر', 'El Darb El Ahmar'],
            ['بولاق', 'Boulaq'],
            ['الوايلي', 'El Waily'],
            ['الخليفة', 'El Khalifa'],
            ['المقابر', 'El Maqaber'],
            ['التبين', 'El Tebbin'],
            ['حدائق القبة', 'Hadayek El Qubba'],
            ['الساحل', 'El Sahel'],
            ['روض الفرج', 'Rod El Farag'],
            ['الشرابية', 'El Sharabiya'],
        ],
        'dakahlia' => [
            ['المنصورة', 'Mansoura'],
            ['طلخا', 'Talkha'],
            ['ميت غمر', 'Mit Ghamr'],
            ['أجا', 'Aga'],
            ['شربين', 'Sherbin'],
            ['بلقاس', 'Belqas'],
            ['المنزلة', 'El Manzala'],
            ['السنبلاوين', 'El Senbellawein'],
            ['جمصة', 'Gamasa'],
            ['دكرنس', 'Dekernes'],
            ['نبروه', 'Nabaroh'],
            ['بني عبيد', 'Bani Ubaid'],
            ['ميت سلسيل', 'Mit Salsil'],
            ['الكردي', 'El Kurdi'],
            ['تمي الأمديد', 'Tami El Amdid'],
            ['منية النصر', 'Minyat El Nasr'],
            ['المطرية', 'El Matariya Dakahlia'],
            ['محلة دمنة', 'Mahallat Damana'],
        ],
        'damietta' => [
            ['دمياط', 'Damietta'],
            ['دمياط الجديدة', 'New Damietta'],
            ['فارسكور', 'Faraskur'],
            ['كفر سعد', 'Kafr Saad'],
            ['كفر البطيخ', 'Kafr El Battikh'],
            ['الزرقا', 'El Zarka'],
            ['رأس البر', 'Ras El Bar'],
            ['الروضة', 'El Rawda'],
            ['ميت أبو غالب', 'Mit Abu Ghalib'],
        ],
        'fayoum' => [
            ['الفيوم', 'Fayoum'],
            ['الفيوم الجديدة', 'New Fayoum'],
            ['طامية', 'Tamiya'],
            ['سنورس', 'Sinnuris'],
            ['إطسا', 'Etsa'],
            ['إبشواي', 'Ibshway'],
            ['يوسف الصديق', 'Youssef El Seddik'],
        ],
        'giza' => [
            ['الجيزة', 'Giza'],
            ['السادس من أكتوبر', '6th of October'],
            ['الشيخ زايد', 'Sheikh Zayed'],
            ['الهرم', 'Al Haram'],
            ['فيصل', 'Faisal'],
            ['إمبابة', 'Imbaba'],
            ['بولاق الدكرور', 'Bulaq El Dakrur'],
            ['البدرشين', 'El Badrashin'],
            ['أطفيح', 'Atfih'],
            ['أبو النمرس', 'Abu El Nomros'],
            ['الصف', 'El Saff'],
            ['العياط', 'El Ayyat'],
            ['الواحات البحرية', 'Bahariya Oasis'],
            ['الحوامدية', 'El Hawamdeya'],
            ['منشأة القناطر', "Manshiyat El Qanater"],
            ['كرداسة', 'Kerdasa'],
            ['كفر غطاطي', 'Kafr Ghatati'],
            ['ميت رهينة', 'Mit Rahina'],
            ['أوسيم', 'Oseim'],
            ['الدقي', 'El Dokki'],
            ['المهندسين', 'El Mohandessin'],
            ['العجوزة', 'El Agouza'],
            ['بين السرايات', 'Bein El Sarayat'],
        ],
        'ismailia' => [
            ['الإسماعيلية', 'Ismailia'],
            ['فايد', 'Fayed'],
            ['القنطرة شرق', 'Qantara Sharq'],
            ['القنطرة غرب', 'Qantara Gharb'],
            ['التل الكبير', 'El Tal El Kebir'],
            ['أبو صوير', 'Abu Suweir'],
            ['القصاصين الجديدة', 'New Qasaseen'],
            ['نفيشة', 'Nefisha'],
        ],
        'kafr-el-sheikh' => [
            ['كفر الشيخ', 'Kafr El Sheikh'],
            ['دسوق', 'Desouk'],
            ['فوه', 'Fouh'],
            ['مطوبس', 'Metoubes'],
            ['برج البرلس', 'Borg El Burullus'],
            ['بيلا', 'Bila'],
            ['الرياض', 'El Riyadh'],
            ['سيدي سالم', 'Sidi Salem'],
            ['قلين', 'Qellin'],
            ['الحامول', 'El Hamoul'],
            ['بلطيم', 'Baltim'],
        ],
        'luxor' => [
            ['الأقصر', 'Luxor'],
            ['إسنا', 'Esna'],
            ['أرمنت', 'Armant'],
            ['الطود', 'El Tod'],
            ['البياضية', 'El Bayadeya'],
            ['القرنة', 'El Qarna'],
            ['الزينية', 'El Zinia'],
        ],
        'menofia' => [
            ['شبين الكوم', 'Shibin El Kom'],
            ['منوف', 'Menouf'],
            ['قويسنا', 'Quesna'],
            ['بركة السبع', 'Berkat El Sab'],
            ['تلا', 'Tala'],
            ['أشمون', 'Ashmoun'],
            ['الباجور', 'El Bagour'],
            ['السادات', 'El Sadat'],
            ['سرس الليان', 'Sars El Layan'],
        ],
        'minya' => [
            ['المنيا', 'Minya'],
            ['المنيا الجديدة', 'New Minya'],
            ['أبو قرقاص', 'Abu Qurqas'],
            ['بني مزار', 'Beni Mazar'],
            ['ملوي', 'Mallawi'],
            ['مطاي', 'Matai'],
            ['مغاغة', 'Maghagha'],
            ['سمالوط', 'Samalut'],
            ['دير مواس', 'Deir Mawas'],
            ['العدوة', 'El Adwa'],
        ],
        'new-valley' => [
            ['الخارجة', 'Kharga'],
            ['الداخلة', 'Dakhla'],
            ['الفرافرة', 'Farafra'],
            ['بلاط', 'Balat'],
            ['باريس', 'Paris'],
            ['موط', 'Mut'],
        ],
        'north-sinai' => [
            ['العريش', 'Arish'],
            ['بئر العبد', 'Bir El Abd'],
            ['الشيخ زويد', 'Sheikh Zuweid'],
            ['رفح', 'Rafah'],
            ['الحسنة', 'El Hasana'],
            ['نخل', 'Nakhl'],
        ],
        'port-said' => [
            ['بورسعيد', 'Port Said'],
            ['بورفؤاد', 'Port Fouad'],
            ['المناخ', 'El Manakh'],
            ['الشرق', 'El Sharq'],
            ['العرب', 'El Arab'],
            ['الضواحي', 'El Dawahy'],
            ['الزهور', 'El Zohour'],
        ],
        'qalyubia' => [
            ['بنها', 'Banha'],
            ['قليوب', 'Qalyub'],
            ['شبرا الخيمة', 'Shubra El Kheima'],
            ['الخانكة', 'El Khanka'],
            ['الخصوص', 'El Khusus'],
            ['طوخ', 'Tukh'],
            ['قها', 'Qaha'],
            ['القناطر الخيرية', 'El Qanater El Khayreya'],
            ['العبور', 'El Obour'],
            ['كفر شكر', 'Kafr Shukr'],
            ['شبين القناطر', 'Shibin El Qanater'],
        ],
        'qena' => [
            ['قنا', 'Qena'],
            ['قنا الجديدة', 'New Qena'],
            ['نقادة', 'Naqada'],
            ['قوص', 'Qus'],
            ['فرشوط', 'Farshut'],
            ['دشنا', 'Dishna'],
            ['أبو تشت', 'Abu Tesht'],
            ['نجع حمادي', 'Nag Hammadi'],
            ['قفط', 'Qift'],
        ],
        'red-sea' => [
            ['الغردقة', 'Hurghada'],
            ['سفاجا', 'Safaga'],
            ['القصير', 'El Quseir'],
            ['مرسى علم', 'Marsa Alam'],
            ['رأس غارب', 'Ras Gharib'],
            ['حلايب', 'Halayeb'],
            ['شلاتين', 'Shalateen'],
            ['برنيس', 'Berenice'],
            ['الجونة', 'El Gouna'],
        ],
        'sharqia' => [
            ['الزقازيق', 'Zagazig'],
            ['العاشر من رمضان', '10th of Ramadan'],
            ['بلبيس', 'Belbeis'],
            ['مشتول السوق', 'Mashtul El Suq'],
            ['أبو حماد', 'Abu Hammad'],
            ['أبو كبير', 'Abu Kebir'],
            ['فاقوس', 'Faqous'],
            ['ههيا', 'Hihia'],
            ['الحسينية', 'El Husseiniya'],
            ['الإبراهيمية', 'El Ibrahimiya'],
            ['كفر صقر', 'Kafr Saqr'],
            ['القنايات', 'El Qanayat'],
            ['منشأة أبو عمر', 'Manshiyat Abu Omar'],
            ['منيا القمح', 'Minya El Qamh'],
            ['القرين', 'El Qurein'],
            ['الصالحية الجديدة', 'El Salhiya El Gedida'],
            ['صان الحجر', 'San El Hagar'],
            ['أولاد صقر', 'Awlad Saqr'],
            ['ديرب نجم', 'Dirb Negm'],
        ],
        'sohag' => [
            ['سوهاج', 'Sohag'],
            ['سوهاج الجديدة', 'New Sohag'],
            ['أخميم', 'Akhmim'],
            ['أخميم الجديدة', 'New Akhmim'],
            ['طما', 'Tama'],
            ['طهطا', 'Tahta'],
            ['المنشاة', 'El Munshah'],
            ['دار السلام', 'Dar El Salam'],
            ['ساقلتة', 'Saqulta'],
            ['جرجا', 'Girga'],
            ['المراغة', 'El Maragha'],
            ['البلينا', 'El Baliana'],
            ['جهينة', 'Juhayna'],
            ['أولاد طوق شرق', 'Awlad Toq Sharq'],
        ],
        'south-sinai' => [
            ['شرم الشيخ', 'Sharm El Sheikh'],
            ['دهب', 'Dahab'],
            ['نويبع', 'Nuweiba'],
            ['طابا', 'Taba'],
            ['سانت كاترين', 'Saint Catherine'],
            ['الطور', 'El Tor'],
            ['رأس سدر', 'Ras Sedr'],
            ['أبو زنيمة', 'Abu Zenima'],
            ['أبو رديس', 'Abu Rudeis'],
        ],
        'suez' => [
            ['السويس', 'Suez'],
            ['عتاقة', 'Ataqa'],
            ['الأربعين', 'El Arbaeen'],
            ['فيصل', 'Faisal'],
            ['الجناين', 'El Ganayen'],
            ['عين الصخنة', 'Ain Sokhna'],
        ],
        'suez-gharbia' => [
            ['طنطا', 'Tanta'],
            ['المحلة الكبرى', 'El Mahalla El Kubra'],
            ['كفر الزيات', 'Kafr El Zayat'],
            ['زفتى', 'Zifta'],
            ['سمنود', 'Samannoud'],
            ['بسيون', 'Basyoun'],
            ['قطور', 'Qotor'],
            ['السنطة', 'El Santa'],
            ['السويس', 'Suez'],
            ['عتاقة', 'Ataqa'],
        ],
    ];

    public function run(): void
    {
        foreach ($this->citiesByGovernorate as $slug => $cities) {
            $gov = Governorate::where('slug', $slug)->first();
            if (!$gov) {
                $this->command->warn("Governorate not found, skipping: {$slug}");
                continue;
            }

            $created = 0;
            $skipped = 0;
            foreach ($cities as [$nameAr, $nameEn]) {
                $exists = $gov->cities()
                    ->where('name->en', $nameEn)
                    ->exists();
                if ($exists) {
                    $skipped++;
                    continue;
                }
                $gov->cities()->create([
                    'name' => ['ar' => $nameAr, 'en' => $nameEn],
                ]);
                $created++;
            }

            $this->command->info("[{$slug}] created: {$created}, already-present: {$skipped}");
        }
    }
}
